# Generated by Django 5.0.6 on 2024-07-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(max_length=26)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('is_second_hand', models.BooleanField(default=False)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('product_series', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(default=1)),
            ],
            options={
                'unique_together': {('upc', 'is_second_hand')},
            },
        ),
    ]
